from .abitterfeld import abitterfeld
from .halle import halle
from .harz import harz
from .land import sanhalt
from .magdeburg import magdeburg
from .saalekreis import saalekreis
from .salzlandkreis import salzlandkreis
from .stendal import stendal
from .wittenberg import wittenberg
