from .lgl import lgl
from .ansbach import ansbach
from .augsburg import augsburg
from .badkissingen import badkissingen
from .bamberg import bamberg
from .bayreuth import bayreuth
from .cham import cham
from .ebersberg import ebersberg
from .ffb import ffb
#from .forchheim import forchheim
from .dingolfing import dingolfing
from .garmisch import garmisch
from .hassberge import hassberge
from .ingolstadt import ingolstadt
from .kitzingen import kitzingen
from .kulmbach import kulmbach
from .landsberg import landsberg
from .lichtenfels import lichtenfels
from .mainspessart import mainspessart
from .miltenberg import miltenberg
from .muenchen import muenchen
from .muenchenlk import muenchenlk
from .nea import nea
from .neuburg import neuburg
from .pfaffenhofen import pfaffenhofen
from .rottal import rottal
#from .starnberg import starnberg
from .tirschenreuth import tirschenreuth
from .traunstein import traunstein
from .wschongau import wschongau
from .wunsiedel import wunsiedel
